### PR TITLE
Fix testing with non-default database and in-memory pdo databases.

### PR DESCRIPTION
**Pull request by leth**
As mentioned in #65

### CODE REVIEW

**Comment by leth** [comment]
This isn't going to apply cleanly after 5ae46e8691d5c59b1238 :(

**Comment by creatoro** [comment]
I'll just add it by hand :)

**Comment by leth** [comment]
The first two commits should cherry-pick ok :)

**Comment by leth** [comment]
Next time, if you could use cherry-pick to add those commits it'd be appreciated. 3 of the 4 would have applied fine.

You'd just need to fetch the commits from my repo (`git fetch foobar`) then use `git cherry-pick <commit hash>` to apply each commit to your branch.

**Comment by creatoro** [comment]
@leth: I'll try, but I didn't know how to do it until now :).
I wanted to make some minor modifications to your code anyway.

I'll merge your coding style changes soon.

Edit: just did it... Cherry picking is fun! Thanks @leth.

**Comment by leth** [comment]
I've re-based all my branches off yours again. It took some time, but I'm getting more confident with magical git commands now :P

For what it's worth, I still feel like I'm learning git, I'm alright handling branches but complicated merges or rebasing still throws me a bit.

Edit: Merges are better than cherry picks, but obviously you can't always merge.

**Comment by leth** [comment]
Also: find yourself a good commit network visualiser, it helps a lot in understanding what's going on :)
I use http://gitx.frim.nl/seeit.html#screenshots but it's mac only.

**Comment by creatoro** [comment]
Check this one out: http://www.syntevo.com/smartgit/index.html

**Comment by leth** [comment]
Cool!

**Pull request closed without merging**
